movieblog/movieblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from movies import views as movieviews
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('movies.urls', namespace='movies')),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings', app_name='ratings')),
    url(r'bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^movies/', movieviews.movie_list, name='movies_list'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movieblog/movies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movies/(?P<movie_pk>\d+)/$', views.movie_detail, name='detail'),
    url(r'^movies/add$', views.movie_add, name='add'),
]

movieblog/movies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField
from django.db.models import Avg
from django.urls import reverse

# A function that returns a created path to a movie cover


def cover_upload_path(instance, filename):
    return '/'.join(['cover', instance.category.name, filename])


class Movie(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey('movies.Category')
    description = models.TextField(max_length=140)
    release_date = models.DateField(default=timezone.now)
    director = models.ForeignKey('movies.Director')
    actor = models.ManyToManyField('movies.Actor')
    country = CountryField()
    cover_img = models.ImageField(
        upload_to=cover_upload_path, default='/covers/default_cover.jpeg', null=True)

    class Meta:
        ordering = ['-release_date']

    def __unicode__(self):
        return "%s" % (self.title)

    def avg_rating(self):
        return self.reviews.all().aggregate(Avg('rating')).get('rating__avg', None)

    def get_absolute_url(self):
        return reverse('movies:detail', args=(self.pk,))


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    country = CountryField()

    def __unicode__(self):
        return "%s, %s" % (self.first_name, self.last_name)

    class Meta:
        abstract = True


class Director(Person):
    pass


class Actor(Person):
    pass


class Category(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField()

    def __unicode__(self):
        return "%s" % (self.name)

movieblog/movies/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from .models import Movie


class MovieForm(ModelForm):

    class Meta:
        model = Movie
        fields = ['title', 'category',
                  'description', 'release_date', 'country', 'director', 'actor', ]

movieblog/movies/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from movies.forms import MovieForm
from reviews.forms import ReviewForm
from .models import Movie, Category


def index(request):
    latest_movies = Movie.objects.all().order_by('-release_date')[:10]
    context = {
        'categories': Category.objects.all(),
        'latest_movies': latest_movies,
    }
    return render(request, 'index.html', context)


def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    error = ''
    recommendations = Movie.objects.filter(
        category=movie.category).exclude(pk=movie_pk)

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)

        if request.user.is_authenticated():
            if review_form.is_valid():
                new_review = review_form.save(commit=False)
                new_review.movie = movie
                new_review.user = request.user
                new_review.save()

                return redirect(reverse('movies:detail', args=(movie.pk, )))
        else:
            error = 'Debes estar logeado para dejar una review'

    review_form = ReviewForm()

    avg_rating = Movie.avg_rating(movie)

    if request.user.is_staff:
        reviews = movie.reviews.a_moderar()
    else:
        reviews = movie.reviews.aceptado()

    context = {'movie': movie, 'review_form': review_form,
               'error': error, 'avg_rating': avg_rating, 'recommendations': recommendations, 'reviews': reviews}
    return render(request, 'movie_detail.html', context)


@login_required()
@user_passes_test(lambda u: u.is_staff, login_url='/login/')
def movie_add(request):
    error = ''
    if request.method == 'POST':
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            # Si el form es valido guardar la data en una variable sin pegarle a la
            # base de datos, para agregar info que esta en el request
            new_movie = movie_form.save(commit=False)
            # Agregar user desde request
            new_movie.user = request.user
            # Guardar en base de datos
            new_movie.save()
            return redirect(reverse('movies:index'))
        else:
            error = 'El formulario no es valido'
    else:
        movie_form = MovieForm()
    context = {'movie_form': movie_form, 'error': error}
    return render(request, 'movie_add.html', context)


def movie_list(request):
    category = request.GET.get('category')
    movies = Movie.objects.all()
    if category:
        movies = movies.filter(category__pk=category)
    categories = Category.objects.all()
    paginator = Paginator(movies, 2)
    page = request.GET.get('page')
    try:
        movie_page = paginator.page(page)
    except PageNotAnInteger:
        movie_page = paginator.page(1)
    except EmptyPage:
        movie_page = paginator.page(paginator.num_pages)
    context = {
        'movies': movies,
        'categories': categories,
        'movie_page': movie_page,
    }
    return render(request, 'movie_list.html', context)

movieblog/movies/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <title>Hello, world!</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <p> WELCOME! </p>
      </div>
      <div class="row">
        <div class="col">
          {% if user.is_authenticated %}
          <p><a href="{% url 'account_logout' %}">Logout</a></p>
          {% else %}
          <p><a href="{% url 'account_login' %}">Login</a> or <a href="{% url 'account_signup' %}">Sign up</a> if you don't have an account!</p>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
            <p><a href="{% url 'movies:add' %}">Agregar pelicula</a></p>
        </div>
        <div class="col-md-4">
            {% for movie in movies %}
              <p><a href="{% url 'movies:detail' movie.pk %}">{{ movie.release_date }} | {{ movie }}</a></p>
            {% endfor %}
        </div>
        <div class="col-md-4">
            {% for category in categories %}
              <p><a href="">{{ category }}</a></p>
            {% endfor %}
        </div>
      </div>
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

movieblog/movies/templates/movie_add.html
<h1>Cargar nueva pelicula:</h1>

{% if user.is_staff %}
	<form method='POST'>
		{% csrf_token %}
		{{ movie_form.as_p }}
		<input type="submit" name="Guardar">
	</form>
{% else %}
	<p>Debes estar logueado en una cuenta tipo staff para cargar peliculas </p><a href = "{% url 'login' %}">Login</a>

{% endif %}

movieblog/movies/templates/movie_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="container" style='padding-top: 4rem;'>
		<div class="row no-gutter">
			<div class="col-8">
				<div class="page-header">
					<p class="sanserif"><h1>{{ movie }}</h1>
					<small>Average Review Rating: {{ avg_rating }}</small>
					</p>
					<p>Resume: {{ movie.description }}</p>
					<p>Category: {{ movie.category }}</p>
					<p>Director: {{ movie.director }}</p>
				</div>
			</div>
			<div class="col-4">
				<img src="{{ movie.cover_img.url }}">
			</div>
		</div>
		<div class="row no-gutter">
			<div class="col-12">
				<div class="page-header">
					<h3>Reviews</h3>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				{% for review in reviews %}
					<div class="row">
						<p> <a href="{{ review.get_absolute_url }}"><small>"{{ review.title }}" </a>  by {{ review.user }}</small> </p>
					</div>
				{% endfor %}
			</div>
			<div class="col">
				{% if user.is_authenticated %}
					<form method='POST'>
						{% csrf_token %}
						{{ review_form.as_p }}
						<input type="submit" name="Guardar">
					</form>
				{% else %}
					<a href="{% url 'account_login' %}"><h4>Ingresa para dejar tu review</h4></a>
				{% endif %}
			</div>
		</div>
		<div class="row">
			{% for movie1 in recommendations %}
				<div class="col">
					<h5>{{ movie1.title }}</h5>
					<img src="{{ movie1.cover_img.url }}">
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

movieblog/movies/templates/movie_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style='padding-top: 6rem;'>
	<div class="row">
		<div class="col-10">
			<div class="row">
			{% for movie in movie_page %}
				<div class="card-center">
			         <img src="{{ movie.cover_img.url }}" alt="Card image cap">
			         <div class="card-block">
			            <h5 class="card-title">{{ movie.title }}</h5>
			            <h6 class="car-subtitle">{{ movie.category }}</h6>
			            <p class="card-text">{{ movie.description|truncatechars:140 }}</p>
			            <a href="{{ movie.get_absolute_url }}" class="btn btn-primary">See detail</a>
			         </div>
			     </div>
			{% endfor %}
			</div>
		</div>
		<div class="col-2">
			<div class="list-group">
				{% for category in categories %}
				   <a href="?category={{ category.pk }}" class="list-group-item list-group-item-action">{{ category.name }}</a>
				{% endfor %}
			</div>
		</div>
	</div>
</div>


<div class="pagination">
    <span class="step-links">
        {% if movie_page.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ movie_page.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ movie_page.number }} of {{ movie_page.paginator.num_pages }}.
        </span>

        {% if movie_page.has_next %}
            <a href="?page={{ movie_page.next_page_number }}">next</a>
            <a href="?page={{ movie_page.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock %}