movieblog/movieblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from movies import views as movieviews
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('movies.urls', namespace='movies')),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings', app_name='ratings')),
    url(r'bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^movies/', movieviews.movie_list, name='movies_list'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movieblog/movies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movies/(?P<movie_pk>\d+)/$', views.movie_detail, name='detail'),
    url(r'^movies/add$', views.movie_add, name='add'),
]

movieblog/movieblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Album example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'movies_list' %}">Movies</a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'movies:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies_list' %}">Movies</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.is_authenticated %}{{ user }}{% else %}Ingresar{% endif %}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'account_logout' %}">Salir</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'account_login' %}">Ingresar</a>
                <a class="dropdown-item" href="{% url 'account_signup' %}">Registrarse</a>
              {% endif %}
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
    src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
    crossorigin="anonymous"></script>
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.4/holder.min.js"></script>
    <script>
      $(function () {
        Holder.addTheme("thumb", { background: "#55595c", foreground: "#eceeef", text: "Thumbnail" });
      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script type="text/javascript" src='{% static "js/csrf.js" %}'></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

movieblog/movieblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary">Main call to action</a>
          <a href="#" class="btn btn-secondary">Secondary action</a>
        </p>
      </div>
  </section>

    <div class="album text-muted">
      <div class="container">
        <div class="row">
           {% for movie in latest_movies %} 
              <div class="card">
                 <img src="{{ movie.cover_img.url }}" alt="Card image cap">
                 <div class="card-block">
                    <h6 class="card-title">{{ movie.title }}</h6>
                    <h5 class="car-subtitle">{{ movie.category }}</h5>
                    <p class="card-text">{{ movie.description|truncatechars:140 }}</p>
                    <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">See detail</a>
                 </div>
              </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}